name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-deb-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential debhelper dh-make fakeroot lintian nodejs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify Node.js
        run: |
          node --version
          npm --version

      - name: Prepare build directory
        run: |
          VERSION="21.0.4"
          mkdir -p "nx-${VERSION}"
          rsync -av --exclude='.git*' --exclude='*.deb' ./ "nx-${VERSION}/"
          cd "nx-${VERSION}"
          cat > debian/changelog << EOF
          nx (${VERSION}-1) unstable; urgency=medium

            * CI build for testing

           -- CI Builder <ci@example.com>  $(date -R)
          EOF

      - name: Build .deb package
        run: |
          cd nx-21.0.4
          debuild -us -uc -b

      - name: Install .deb package
        run: |
          sudo apt-get install -y ./nx_*.deb

      - name: Test nx command
        run: |
          nx --version
